<?php
return array (
  'lajiao' => 
  array (
    'status' => '1',
    'from' => 'lajiao',
    'show' => 'LJ',
    'des' => '辣椒资源',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://lajiaoapi.com/watch?url=',
    'sort' => '8997',
    'tip' => '',
    'id' => 'lajiao',
  ),
  'dadim3u8' => 
  array (
    'status' => '1',
    'from' => 'dadim3u8',
    'show' => 'DD',
    'des' => '大地资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8996',
    'tip' => '',
    'id' => 'dadim3u8',
  ),
  's8m3u8' => 
  array (
    'status' => '1',
    'from' => 's8m3u8',
    'show' => 'X8',
    'des' => '杏吧资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8995',
    'tip' => '',
    'id' => 's8m3u8',
  ),
  'lbm3u8' => 
  array (
    'status' => '1',
    'from' => 'lbm3u8',
    'show' => 'LB',
    'des' => '乐播资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8994',
    'tip' => '',
    'id' => 'lbm3u8',
  ),
  'didi' => 
  array (
    'status' => '1',
    'from' => 'didi',
    'show' => 'DD',
    'des' => '滴滴资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8993',
    'tip' => '',
    'id' => 'didi',
  ),
  'smzy' => 
  array (
    'status' => '1',
    'from' => 'smzy',
    'show' => 'SM',
    'des' => '色猫资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8992',
    'tip' => '',
    'id' => 'smzy',
  ),
  'naixx' => 
  array (
    'status' => '1',
    'from' => 'naixx',
    'show' => 'NXX',
    'des' => '奶香香资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8991',
    'tip' => '',
  ),
  'aosika' => 
  array (
    'status' => '1',
    'from' => 'aosika',
    'show' => 'ASK',
    'des' => '奥斯卡资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8990',
    'tip' => '',
    'id' => 'aosika',
  ),
  'slm3u8' => 
  array (
    'status' => '1',
    'from' => 'slm3u8',
    'show' => 'SL',
    'des' => '森林资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8987',
    'tip' => '',
    'id' => 'slm3u8',
  ),
  'swm3u8' => 
  array (
    'status' => '1',
    'from' => 'swm3u8',
    'show' => 'SW',
    'des' => '色窝资源/丝袜资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8985',
    'tip' => '',
    'id' => 'swm3u8',
  ),
  'ytm3u8' => 
  array (
    'status' => '1',
    'from' => 'ytm3u8',
    'show' => 'YT',
    'des' => '玉兔资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8984',
    'tip' => '',
    'id' => 'ytm3u8',
  ),
  '155m3u8' => 
  array (
    'status' => '1',
    'from' => '155m3u8',
    'show' => '155',
    'des' => '155资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '8983',
    'tip' => '',
    'id' => '155m3u8',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
);