DELETE FROM `mac_type`;
INSERT INTO `mac_type` (`type_id`, `type_name`, `type_en`, `type_sort`, `type_mid`, `type_pid`, `type_status`, `type_tpl`, `type_tpl_list`, `type_tpl_detail`, `type_tpl_play`, `type_tpl_down`, `type_key`, `type_des`, `type_title`, `type_union`, `type_extend`, `type_logo`, `type_pic`, `type_jumpurl`) VALUES
(16, '拳击', 'quanji', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(17, '台球', 'taiqiu', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(18, '高尔夫', 'gaoerfu', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(19, '橄榄球', 'ganlanqiu', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(20, '摩托车', 'motuoche', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(21, '棒球', 'bangqiu', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(22, '自行车', 'zixingche', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(23, '赛车', 'saiche', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(24, 'WWE摔跤', 'WWEshuaijiao', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(25, '网球', 'wangqiu', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(26, '足球', 'zuqiu', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(27, '篮球', 'lanqiu', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(28, '奇幻片', 'qihuanpian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(29, '动作片', 'dongzuopian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(30, '影视资讯', 'yingshizixun', 0, 2, 74, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(31, '明星资讯', 'mingxingzixun', 0, 2, 74, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(32, '喜剧片', 'xijupian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(33, '海外动漫', 'haiwaidongman', 0, 1, 76, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(34, '综合三级', 'sanjilunli', 0, 1, 75, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(35, '欧美动漫', 'oumeidongman', 0, 1, 76, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(36, '日韩动漫', 'rihandongman', 0, 1, 76, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(37, '大陆动漫', 'daludongman', 0, 1, 76, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(38, '欧美综艺', 'oumeizongyi', 0, 1, 77, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(39, '港台综艺', 'gangtaizongyi', 0, 1, 77, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(40, '日韩综艺', 'rihanzongyi', 0, 1, 77, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(41, '大陆综艺', 'daluzongyi', 0, 1, 77, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(42, '泰国剧', 'taiguoju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(43, '海外剧', 'haiwaiju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(44, '日本剧', 'ribenju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(45, '犯罪片', 'fanzuipian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(46, '爱情片', 'aiqingpian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(47, '科幻片', 'kehuanpian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(48, '恐布片', 'kongbupian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(49, '剧情片', 'juqingpian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(50, '战争片', 'zhanzhengpian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(51, '悬疑片', 'lunlipian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(52, '动画片', 'jilupian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(53, '伦理片', 'lunlipian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(54, '纪录片', 'jilupian', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(55, '大陆剧', 'daluju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(56, '香港剧', 'xianggangju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(57, '台湾剧', 'taiwanju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(58, '欧美剧', 'oumeiju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(59, '韩国剧', 'hanguoju', 0, 1, 78, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(60, '荧幕热星', 'yingmurexing', 0, 8, 80, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(61, 'MMA综合格斗', 'MMAzonghegedou', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(62, 'UFC终极格斗', 'UFCzhongjigedou', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(63, '写真资源', 'xiezhenziyuan', 0, 1, 84, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(64, '韩国伦理', 'hanguolunli', 0, 1, 75, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(65, '香港三级', 'xianggangsanji', 0, 1, 75, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(66, '西方伦理', 'xifanglunli', 0, 1, 75, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(67, '电视直播', 'dianshizhibo', 0, 1, 83, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(68, '综合赛事', 'zonghesaishi', 0, 1, 82, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(69, '娱乐八卦', 'yulebagua', 0, 1, 74, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(70, '影视预告', 'yingshiyugao', 0, 1, 74, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(71, '微电影', 'weidianying', 0, 1, 79, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(72, '韩国美女', 'hanguomeinv', 0, 1, 84, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(73, '主播美女', 'zhubomeinv', 0, 1, 84, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(74, '资讯', 'zixun', 8000, 2, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(75, '伦理', 'lunli', 500, 1, 0, 1, 'type.html', 'show.html', 'detail.html', 'play.html', 'down.html', '', '', '', '', '', '', '', ''),
(76, '动漫', 'dongman', 300, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(77, '综艺', 'zongyi', 400, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(78, '连续剧', 'lianxuju', 200, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(79, '电影', 'dianying', 100, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(80, '明星', 'mingxing', 9000, 8, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(81, '电影解说', 'dianyingjieshui', 700, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(82, '体育', 'tiyu', 600, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(83, '直播', 'zhibo', 9000, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', ''),
(84, '福利', 'fuli', 800, 1, 0, 1, 'type.html', 'show.html', 'detail.html', '', '', '', '', '', '', '', '', '', '');


DELETE FROM `mac_collect`;
INSERT INTO `mac_collect` (`collect_id`, `collect_name`, `collect_url`, `collect_type`, `collect_mid`, `collect_appid`, `collect_appkey`, `collect_param`, `collect_filter`, `collect_filter_from`, `collect_opt`, `collect_sync_pic_opt`) VALUES
(78, '魔都资源', 'https://www.moduzy.com/api.php/provide/vod/from/modum3u8/at/json', 0, 1, '', '', '', 0, 'modu', 0, 0),
(77, '速播资源', 'https://subocaiji.com/api.php/provide/vod/from/subm3u8/at/json', 0, 1, '', '', '', 0, 'subo', 0, 0),
(76, '极速资源', 'https://jszyapi.com/api.php/provide/vod/from/jsm3u8/at/json', 0, 1, '', '', '', 0, 'jisu', 0, 0),
(75, '大漠资源', 'https://damozy.com/api.php/provide/vod/from/M3U8/at/json/', 0, 1, '', '', '', 0, 'damo', 0, 0),
(73, '非凡资源', 'https://cj.ffzyapi.com/api.php/provide/vod/from/ffm3u8/at/json/', 0, 1, '', '', '', 0, 'feifan', 0, 0),
(72, 'U酷资源', 'https://api.ukuapi.com/api.php/provide/vod/from/ukm3u8/at/json', 0, 1, '', '', '', 0, 'uku', 0, 0),
(74, '海外看资源', 'https://haiwaikan.com/api.php/provide/vod/from/haiwaikan/at/json', 0, 1, '', '', '', 0, 'haiwaikan', 0, 0),
(71, 'iKun资源', 'https://ikunzyapi.com/api.php/provide/vod/from/ikm3u8/at/json', 0, 1, '', '', '', 0, 'ikun', 0, 0),
(70, '快车资源', 'https://caiji.kczyapi.com/api.php/provide/vod/from/kcm3u8/at/json/', 0, 1, '', '', '', 0, 'NKCRVC', 0, 0),
(69, '光速资源', 'https://api.guangsuapi.com/api.php/provide/vod/from/gsm3u8/at/json/', 0, 1, '', '', '', 0, 'guangsu', 0, 0),
(68, '金鹰资源', 'https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/json', 0, 1, '', '', '', 0, 'jinying', 0, 0),
(67, '新浪资源', 'https://api.xinlangapi.com/xinlangapi.php/provide/vod/from/xlm3u8/at/json', 0, 1, '', '', '', 0, 'xinlang', 0, 0),
(66, '卧龙资源', 'https://collect.wolongzy.cc/api.php/provide/vod/from/wolong/at/json', 0, 1, '', '', '', 0, 'wolongz', 0, 0),
(65, '优质资源', 'https://api.1080zyku.com/inc/api_mac10.php', 0, 1, '', '', '', 0, 'youzhi', 0, 0),
(64, '红牛资源', 'https://www.hongniuzy2.com/api.php/provide/vod/from/hnm3u8/at/json', 0, 1, '', '', '', 0, 'hongniu', 0, 0),
(63, '无尽资源', 'https://api.wujinapi.me/api.php/provide/vod/from/wjm3u8/at/json', 0, 1, '', '', '', 0, 'wujin', 0, 0),
(62, '百度资源', 'https://api.apibdzy.com/api.php/provide/vod/from/dbm3u8/at/json', 0, 1, '', '', '', 0, 'baiduyun', 0, 0),
(61, '樱花资源', 'https://m3u8.apiyhzy.com/api.php/provide/vod/from/yhm3u8/at/json', 0, 1, '', '', '', 0, 'yinghua', 0, 0),
(60, '闪电资源', 'https://sdzyapi.com/api.php/provide/vod/from/sdm3u8/at/json', 0, 1, '', '', '', 0, 'shandian', 0, 0),
(59, '飞速资源', 'https://www.feisuzyapi.com/api.php/provide/vod/from/fsm3u8/at/json', 0, 1, '', '', '', 0, 'feisu', 0, 0);
